function makeNewFunction(str)
%makeNewFunction Makes a new function file with a pre-formatted H1 text.

tok = '<end_of_pre_formatted_H1>';   %token to delimit the default H1

switch getenv('username')
    case 'cs1414'
        name  = 'Christopher Szczyglowski';
        email = 'chris.szczyglowski@gmail.com';
    otherwise
        name  = '';
        email = '';
end

if nargin < 1
    %Get function name from user input
    str = inputdlg('Type the name of the new function', 'Set function name');
    if isempty(str)
        warning('No input from user, ending function.');
        return
    else
        str = str{1};
    end
end

assert(isvarname(str), ['Expected the function name to be valid - i.e. ' , ...
    'start with a letter and contain only alphanumeric characters with ' , ...
    'no spaces. Do not specify the file extension as this will be added ', ...
    'automatically.']);

%Write the function template to a file in the current directory
funcFilename = [str, '.m'];
fid = fopen(fullfile(pwd, funcFilename), 'w');
assert(fid ~= -1, 'Unable to open the file ''%s''.', funcFilename);

fprintf(fid, [ ...
    'function outputs = %s()\n', ...
    '%%%s Short explanation of the function...\n%%\n', ...
    '%% Syntax:\n', ...
    '%%\t- Brief explanation of the syntax...\n%%\n', ...
    '%% Detailed Description:\n', ...
    '%%\t- Detailed explanation of the function and how it works...\n%%\n', ...
    '%% References:\n', ...
    '%%\t[1]. "Can quantum-mechanical description of physical reality be\n%%', ...
    '         considered complete?", A Einstein, Physical Review 47(10):777,\n%%', ...
    '         American Physical Society 1935, 0031-899X\n%%\n', ...
    '%% Author    : %s\n', ...
    '%% Email     : %s\n', ...
    '%% Timestamp : %s\n', ...
    '%%\n', ...
    '%% Copyright (c) %s %s\n', ...
    '%% All Rights Reserved\n%%\n%%\n', ...
    '%% Revision: 1.0 %s\n%%\t- Initial function:\n%%\n%% %s\n\nend\n', ...
    ], str, str, name, email, datestr(now), datestr(now, 10), name, datestr(now), tok);

fclose(fid);

end

