function hg = drawNodes(coords, hParent)
%drawNodes Draws a set of node objects and returns the handle.

hg  = line(hParent, ...
    'XData', coords(1, :), ...
    'YData', coords(2, :), ...
    'ZData', coords(3, :), ...
    'LineStyle'      , 'none' , ...
    'Marker'         , 'o'    , ...
    'MarkerFaceColor', 'g'    , ...
    'MarkerEdgeColor', 'k'    , ...
    'Tag'            , 'Nodes', ...
    'SelectionHighlight', 'off');

end

