function hg = drawNodes(coords, hParent, varargin)
%drawNodes Draws a set of node objects and returns the handle.

hg = [];

if isempty(coords)
    return
end

hg  = line(hParent, ...
    'XData', coords(1, :), ...
    'YData', coords(2, :), ...
    'ZData', coords(3, :), ...
    'LineStyle'      , 'none' , ...
    'Marker'         , 'o'    , ...
    'MarkerFaceColor', 'g'    , ...
    'MarkerEdgeColor', 'k'    , ...
    'Tag'            , 'Nodes', ...
    'SelectionHighlight', 'off');

if ~isempty(varargin)
    set(hg, varargin{:});
end

end

