classdef AnalysisData < bulk.BulkData
    %AnalysisData Describes a bulk dat entry which specifies data for a
    %finite element analysis.
    %    
    % Valid Bulk Data Types:
    %   - 'AERO'
    %   - 'FLUTTER'
    %   - 'SPLINE1'
    %   - 'SPLINE2'
    %   - 'EIGR' 
    %   - 'EIGRL'
    
    methods % construction
        function obj = AnalysisData(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'AERO', ...
                'BulkProps'  , {'ACSID', 'VEL', 'REFC', 'RHOREF', 'SYMXZ', 'SYMXY'}, ...
                'PropTypes'  , {'i'    , 'r'  , 'r'   , 'r'     , 'r'    , 'r'    }, ...
                'PropDefault', {0      , 0    , 0     , 0       , 0      , 0      }, ...
                'AttrList'   , {'VEL', {'nonnegative'}, 'REFC', {'nonnegative'}, 'RHOREF', {'nonnegative'}, ...
                'SYMXZ', {'integer'}, 'SYMXY', {'integer'}}, ...
                'Connections', {'ACSID', 'bulk.CoordSystem', 'AeroCoordSys'});
            addBulkDataSet(obj, 'EIGR', ...
                'BulkProps'  , {'SID', 'METHOD', 'F1', 'F2', 'NE', 'ND', 'NORM', 'G', 'C'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'r' , 'r' , 'i' , 'i' , 'c'   , 'i', 'c'}, ...
                'PropDefault', {''   , ''      , 0   , 0   , 0   , 0   , 'MASS', 0  , ''} , ...                
                'AttrList'   , {'NE', {'positive'}});            
            addBulkDataSet(obj, 'EIGRL', ...
                'BulkProps'  , {'SID', 'V1', 'V2', 'ND', 'MSGLVL', 'MAXSET', 'SHFSCL', 'NORM'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'i' , 'r'     , 'r'     , 'r'     , 'c'   }, ...
                'PropDefault', {''   , 0   , 0   , 0   , 0       , 0       , 0       , 'MASS'}, ...                
                'AttrList'   , {'MSGLVL', {'integer', 'nonnegative', '<=' 4}});         
            addBulkDataSet(obj, 'FLUTTER', ...
                'BulkProps'  , {'SID', 'METHOD', 'DENS', 'MACH', 'RFREQ', 'IMETH', 'NVALUE_OMAX', 'EPS'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'i'   , 'i'   , 'i'    , 'c'    , 'i'          , 'r'}  , ...
                'PropDefault', {0    , ''      , 0     , 0     , 0      , 'l'    , 0            ,  1e-3}, ...
                'Connections', {'DENS', 'FLFACT', 'Density', 'MACH', 'FLFACT', 'Mach', 'RFREQ', 'FLFACT', 'ReducedFreq'});
            addBulkDataSet(obj, 'FREQ1', ...
                'BulkProps'  , {'SID', 'F1', 'DF', 'NDF'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'i'}  , ...
                'PropDefault', {''   , ''  , ''  , 0}    , ...                
                'AttrList'   , {'F1', {'nonnegative'}, 'DF', {'nonnegative'}});
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            
        end
    end
        
end

