classdef AnalysisData < bulk.BulkData
    %AnalysisData Describes a bulk dat entry which specifies data for a
    %finite element analysis.
    %    
    % Valid Bulk Data Types:
    %   - 'AERO'
    %   - 'FLUTTER'
    %   - 'SPLINE1'
    %   - 'SPLINE2'
    %   - 'EIGR' 
    %   - 'EIGRL'
    
    methods % construction
        function obj = AnalysisData(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'AERO', ...
                'BulkProps'  , {'ACSID', 'VEL', 'REFC', 'RHOREF', 'SYMXZ', 'SYMXY'}, ...
                'PropTypes'  , {'i'    , 'r'  , 'r'   , 'r'     , 'r'    , 'r'    }, ...
                'PropDefault', {0      , 0    , 0     , 0       , 0      , 0      }, ...
                'AttrList'   , {'VEL', {'nonnegative'}, 'REFC', {'nonnegative'}, 'RHOREF', {'nonnegative'}, ...
                'SYMXZ', {'integer'}, 'SYMXY', {'integer'}}, ...
                'Connections', {'ACSID', 'bulk.CoordSystem', 'AeroCoordSys'});
            addBulkDataSet(obj, 'EIGR', ...
                'BulkProps'  , {'SID', 'METHOD', 'F1', 'F2', 'NE', 'ND', 'NORM', 'G', 'C'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'r' , 'r' , 'i' , 'i' , 'c'   , 'i', 'c'}, ...
                'PropDefault', {''   , ''      , 0   , 0   , 0   , 0   , 'MASS', 0  , ''} , ...                
                'AttrList'   , {'NE', {'positive'}});            
            addBulkDataSet(obj, 'EIGRL', ...
                'BulkProps'  , {'SID', 'V1', 'V2', 'ND', 'MSGLVL', 'MAXSET', 'SHFSCL', 'NORM'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'i' , 'r'     , 'r'     , 'r'     , 'c'   }, ...
                'PropDefault', {''   , 0   , 0   , 0   , 0       , 0       , 0       , 'MASS'}, ...                
                'AttrList'   , {'MSGLVL', {'integer', 'nonnegative', '<=' 4}});         
            addBulkDataSet(obj, 'FLUTTER', ...
                'BulkProps'  , {'SID', 'METHOD', 'DENS', 'MACH', 'RFREQ', 'IMETH', 'NVALUE_OMAX', 'EPS'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'i'   , 'i'   , 'i'    , 'c'    , 'i'          , 'r'}  , ...
                'PropDefault', {0    , ''      , 0     , 0     , 0      , 'l'    , 0            ,  1e-3}, ...
                'Connections', {'DENS', 'FLFACT', 'Density', 'MACH', 'FLFACT', 'Mach', 'RFREQ', 'FLFACT', 'ReducedFreq'});
            addBulkDataSet(obj, 'SPLINE1', ...
                'BulkProps'  , {'EID', 'CAERO', 'BOX1', 'BOX2', 'SETG', 'DZ', 'METH', 'USAGE', 'NELEM', 'MELEM'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'   , 'i'   , 'i'   ,  'r', 'c'   , 'c'    , 'r'    , 'r'}    , ...
                'PropDefault', {''   , ''     , ''    , ''    , ''    , 0   , 'IPS' , 'BOTH' , 10     , 10});
            addBulkDataSet(obj, 'SPLINE2', ...
                'BulkProps'  , {'EID', 'CAERO', 'ID1', 'ID2', 'SETG', 'DZ', 'DTOR', 'CID', 'DTHX', 'DTHY', 'USAGE'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'  , 'i'  , 'i'   , 'r' , 'r'   , 'i'  , 'r'   , 'r'   , 'c'    }, ...
                'PropDefault', {0    , 0      , 0    , 0    , 0     , 0   , 1     , 0    , 'r'   , 'r'   , 'BOTH' }, ...
                'Connections', {'CAERO', 'bulk.AeroPanel', 'AeroPanel', 'SETG', 'bulk.List', 'StrucNode', 'CID', 'bulk.CoordSystem', 'CoordSystem'})
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            
        end
    end
        
end

