classdef BeamProp < bulk.BulkData
    %BeamProp Describes the properties of a bulk.Beam object.
    %
    % The definition of the 'BeamProp' object matches that of the PBEAM
    % bulk data type from MSC.Nastran.
    %
    % Valid Bulk Data Types:
    %   - 'PBEAM'
    %   - 'PBAR'
    %   - 'PROD' - TODO
        
    methods % constructor
        function obj = BeamProp(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'PBAR', ...
                'BulkProps'  , {'PID', 'MID', 'A', 'I1', 'I2', 'J', 'NSM', 'C', 'D', 'E', 'F', 'K', 'I12'}, ...
                'PropTypes'  , {'i'  , 'i'  , 'r', 'r' , 'r' , 'r', 'r'  , 'r', 'r', 'r', 'r', 'r', 'r'}  , ...
                'PropDefault', {''   , ''   , 0  ,  0  , 0   , 0  , 0    , 0  , 0  , 0  , 0  , 0  , 0}    , ...
                'IDProp'     , 'PID', ...
                'PropMask'   , {'C', 2, 'D', 2, 'E', 2, 'F', 2, 'K', 2}, ...
                'Connections', {'MID', 'bulk.Material', 'Materials'}, ...
                'AttrList'   , { ...
                'A', {'nonnegative'}, 'I1' , {'nonnegative'}, 'I2' , {'nonnegative'}, ...
                'J', {'nonnegative'}, 'C'  , {'nrows', 2}   , 'NSM', {'nonnegative'}, ...
                'D', {'nrows', 2}   , 'E'  , {'nrows', 2}   , 'F'  , {'nrows', 2}   , ...
                'K', {'nrows', 2}   , 'I12', {'nonnegative'}});
            addBulkDataSet(obj, 'PBEAM', ...
                'BulkProps'  , { ...
                'PID', 'MID', 'A_A', 'I1_A', 'I2_A', 'I12_A', 'J_A', 'NSM_A', ...
                'C_A', 'D_A', 'E_A', 'F_A', ...
                'SO', 'X_XB', 'A_B', 'I1_B', 'I2_B', 'I12_B', 'J_B', 'NSM_B', ...
                'C_B', 'D_B', 'E_B', 'F_B', ...
                'K', 'S', 'NSIA', 'NSIB', 'CW', ...
                'M_A', 'M_B', 'N_A', 'N_B'}, ...
                'PropTypes'  , { ...
                'i', 'i', 'r', 'r', 'r', 'r', 'r', 'r', ...
                'r', 'r', 'r', 'r', ...
                'c', 'r', 'r', 'r', 'r', 'r', 'r', 'r', ...
                'r', 'r', 'r', 'r', ...
                'r', 'r', 'r', 'r', 'r', ...
                'r', 'r', 'r', 'r'}, ...
                'PropDefault', { ...
                '', '', '', '', '', 0, 0, 0,  ...
                0 , 0 , 0 , 0 , ...
                '', '', 0 , 0 , 0 , 0, 0, 0, ...
                0 , 0 , 0 , 0 , ...
                1, 0, 0, 0, 0 , ...
                0, 0, 0, 0}, ...
                'PropMask'   , { ...
                'C_A', 2, 'D_A', 2, 'E_A', 2, 'F_A', 2, ...
                'C_B', 2, 'D_B', 2, 'E_B', 2, 'F_B', 2, ...
                'K'  , 2, 'S'  , 2, 'CW' , 2, 'M_A', 2, ...
                'M_B', 2, 'N_A', 2, 'N_B', 2}, ...
                'IDProp'     , 'PID', ...
                'Connections', {'MID', 'bulk.Material', 'Materials'}, ...
                'AttrList'   , { ...
                'A_A' , {'nonnegative'}, 'I1_A', {'nonnegative'} , ...
                'I2_A', {'nonnegative'}, 'I12_A', {'nonnegative'}, ...
                'J_A' , {'nonnegative'}, 'NSM_A', {'nonnegative'}, ...
                'C_A' , {'nrows', 2}   , 'D_A'  , {'nrows', 2}   , ...
                'E_A' , {'nrows', 2}   , 'F_A'  , {'nrows', 2}   , ...
                'A_B' , {'nonnegative'}, 'I1_B' , {'nonnegative'}, ...
                'I2_B', {'nonnegative'}, 'I12_B', {'nonnegative'}, ...
                'J_B', {'nonnegative'} , 'NSM_B', {'nonnegative'}, ...
                'C_B', {'nrows', 2}    , 'D_B'  , {'nrows', 2}   , ...
                'E_B', {'nrows', 2}    , 'F_B'  , {'nrows', 2}   , ...
                'K'  , {'nrows', 2}    , 'S'    , {'nrows', 2}   , ...
                'CW' , {'nrows', 2}    , 'M_A'  , {'nrows', 2}   , ...
                'M_B', {'nrows', 2}    , 'N_A'  , {'nrows', 2}   , ...
                'N_B', {'nrows', 2}});
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            
            if strcmp(obj.CardName, 'PBEAM')
                obj.BulkAssignFunction = @assignPBeamData;
            end
            
        end
    end
    
    methods % assigning data during import
        function assignPBeamData(obj, propData, index, BulkMeta)
            %assignPBeamData Assigns data for a PBeam entry to the object.
            %
            % Assumption: The PBEAM data is always fully populated i.e.
            % has 48 sets of data and only one continuation entry.
             
            %If J is not defined then it is the avergate of I1 & I2
            if isempty(propData{1}{ismember(BulkMeta.Names, 'J_A')})
                propData{1}{ismember(BulkMeta.Names, 'J_A')} = ...
                    0.5 * sum(str2num(vertcat(propData{1}{ismember(BulkMeta.Names, {'I1_A', 'I2_A'})}))); %#ok<ST2NM>
            end
            
            %Deal with first two rows (End-A)
            data_endA = horzcat(propData{1 : 2});
            Meta_endA = struct('Names', {BulkMeta.Names(1 : 12)}, ...
                'Format'  , BulkMeta.Format(1 : 16)   , ...
                'Default' , {BulkMeta.Default(1 : 16)}, ...
                'Bounds'  , BulkMeta.Bounds(:, 1 : 12), ...
                'ListProp', {{}});
            assignCardData(obj, data_endA, index, Meta_endA);
            propData([1, 2]) = [];
            if isempty(propData)
                return
            end
            
            %Deal with End-B
            %   - Adjust bounds for indexing as we are dealing with a
            %     subset of the complete data
            idx  = cellfun(@(x) any(contains(x, {'YES', 'YESA', 'NO'})), propData);
            if any(idx)
                data_endB = horzcat(propData{1 : 2});
                Meta_endB = struct('Names', {BulkMeta.Names(13 : 24)}, ...
                    'Format'  , BulkMeta.Format(17 : 32)   , ...
                    'Default' , {BulkMeta.Default(17 : 32)}, ...
                    'Bounds'  , BulkMeta.Bounds(:, 13 : 24) - BulkMeta.Bounds(2, 12), ...
                    'ListProp', {{}});
                assignCardData(obj, data_endB, index, Meta_endB);
                propData([1, 2]) = [];
            end
            if isempty(propData)
                return
            end
            
            %Any remaining data is related to the last two continutations
            data_final = horzcat(propData{:});
            Meta_final = struct('Names', {BulkMeta.Names(25 : end)}, ...
                'Format'  , BulkMeta.Format(33 : end)   , ...
                'Default' , {BulkMeta.Default(33 : end)}, ...
                'Bounds'  , BulkMeta.Bounds(:, 25 : end) - BulkMeta.Bounds(2, 24), ...
                'ListProp', {{}});
            assignCardData(obj, data_final, index, Meta_final);
            
        end
    end
    
end

