classdef List < bulk.BulkData
    %List Describes a set of bulk data that can have an arbitrary number of
    %data points.
    %
    % Valid Bulk Data Types:
    %   - AEFACT
    %   - SET1
    %   - PAERO1
    %   - FLFACT
    
    methods % construction
        function obj = List(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'AEFACT', ...
                'BulkProps'  , {'SID', 'Di'}, ...
                'PropTypes'  , {'i'  , 'r'} , ...
                'PropDefault', {''   , '' } , ...
                'ListProp'   , {'Di'});
            addBulkDataSet(obj, 'SET1', ...
                'BulkProps'  , {'SID', 'Gi'}, ...
                'PropTypes'  , {'i'  , 'r'} , ...
                'PropDefault', {''   , '' } , ...
                'ListProp'   , {'Gi'}, ...
                'Connections', {'Gi', 'bulk.Node', 'Nodes'});
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'PAERO1'   , ...
                'BulkProps'  , {'PID', 'Bi'}, ...
                'PropTypes'  , {'i'  , 'i'} , ...
                'PropDefault', {''   , ''}  , ...
                'ListProp'   , {'Bi'});
            addBulkDataSet(obj, 'FLFACT', ...
                'BulkProps'  , {'SID', 'Fi'}, ...
                'PropTypes'  , {'i'  , 'r' }, ...
                'PropDefault', {0    , 0   }, ...
                'ListProp'   , {'Fi'});
            
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            
            
        end
    end

end

